AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Application superstack

Globals:
  Function:
    Timeout: 3

Resources:
  WebsiteLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: website/template.yaml

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: website
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: website
            DomainName: !GetAtt WebsiteLayer.Outputs.WebsiteDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

Outputs:
  MainURL:
    Description: "Main URL of the website and API (CDN)"
    Value: !Sub "https://${CDN.DomainName}"
