AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Application superstack

Globals:
  Function:
    Timeout: 3

Resources:
  WebsiteLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: website/template.yaml

Outputs:
  WebsiteURL:
    Description: "Static website URL"
    Value: !GetAtt WebsiteLayer.Outputs.WebsiteURL
