AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Application superstack

Resources:
  Website:
    Type: AWS::Serverless::Application
    Properties:
      Location: website/template.yaml

  WebApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: webapi/template.yaml

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          TargetOriginId: website
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
        CacheBehaviors:
          - TargetOriginId: webapi
            PathPattern: "/api/*"
            ViewerProtocolPolicy: https-only
            Compress: true
            AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
            CachedMethods: [GET, HEAD, OPTIONS]
            ForwardedValues:
              QueryString: true
              Headers: [Accept, Referer, Authorization, Content-Type]
        Origins:
          - Id: website
            DomainName: !GetAtt Website.Outputs.WebsiteDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
          - Id: webapi
            DomainName: !GetAtt WebApi.Outputs.WebApiDomainName
            OriginPath: !Sub "/${WebApi.Outputs.WebApiStage}"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

Outputs:
  MainURL:
    Description: "Main URL of the website and API (CDN)"
    Value: !Sub "https://${CDN.DomainName}"
