AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless API

Globals:
  Function:
    Timeout: 3

Parameters:
  AppStage:
    Type: String
    Default: api
    Description: API Gateway stage, used as a prefix for the endpoint URLs
    AllowedPattern: ^[A-Za-z]+$
    MinLength: 1
    MaxLength: 10
    ConstraintDescription: "1-10 Latin letters"

Resources:
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppStage

  ContactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SubmitContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: contacts/
      Handler: submit.lambdaHandler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Environment:
        Variables:
          CONTACTS_S3_BUCKET: !Ref ContactsBucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ContactsBucket
      Events:
        SubmitContact:
          Type: Api
          Properties:
            RestApiId: !Ref WebApi
            Method: post
            Path: /api/contacts

Outputs:
  WebApiStage:
    Description: "API Gateway stage"
    Value: !Ref AppStage
  WebApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"
  WebApiDomainName:
    Description: "API Gateway endpoint URL"
    Value: !Sub "${WebApi}.execute-api.${AWS::Region}.amazonaws.com"
  ContactsBucket:
    Description: "S3 Bucket storing submitted contact details"
    Value: !Ref ContactsBucket
